// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWbP_lQvTIrwZQq_rHg65YppEJ2VbmT_I',
    appId: '1:259748474267:web:091f1b39fa5814dae9453e',
    messagingSenderId: '259748474267',
    projectId: 'intricate-web-498607-t6',
    authDomain: 'intricate-web-498607-t6.firebaseapp.com',
    storageBucket: 'intricate-web-498607-t6.firebasestorage.app',
    measurementId: 'G-MH4G95H7ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWbP_lQvTIrwZQq_rHg65YppEJ2VbmT_I',
    appId: '1:259748474267:android:2b29a5865857b68c01e121', // Note: Run 'flutterfire configure' to update this for mobile
    messagingSenderId: '259748474267',
    projectId: 'intricate-web-498607-t6',
    storageBucket: 'intricate-web-498607-t6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWbP_lQvTIrwZQq_rHg65YppEJ2VbmT_I',
    appId: '1:259748474267:ios:5d5924a14c80f0f501e121', // Note: Run 'flutterfire configure' to update this for mobile
    messagingSenderId: '259748474267',
    projectId: 'intricate-web-498607-t6',
    storageBucket: 'intricate-web-498607-t6.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementSystem',
  );

  static const FirebaseOptions macos = ios;
}
